spring.application.name=ticketflow
spring.threads.virtual.enabled=true
# Configuração do Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Habilitar logs de SQL para vermos o banco trabalhando menos
logging.level.org.hibernate.SQL=DEBUG